### PR TITLE
updating readme and adding portuguese localization

### PR DESCRIPTION
**Pull request by Kazenin**

### CODE REVIEW

**Comment by VxWolf** [comment]
Are the Portugese assault easter egg lines your own or are they direct translations of what we already have?

**Comment by Kazenin** [comment]
I translated using your lines

**Comment by VxWolf** [comment]
Feel free to write your own unique ones

**Comment by Kazenin** [comment]
Easter eggs added, thank you

**Comment by fangedhex** [comment]
Thank you for your translation !

PS : Again... sorry for that late PR validation :(

**Pull request merged**
